---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.11-alpine3.8


inputs:
  - name: source-code

run:
  path: sh
  args:
  - -c
  - |
    set -e -u -x
    export ROOT_DIR=$PWD
    cd source-code/
    CGO_ENABLED=0 GO111MODULE=auto go test -v ./... -mod=vendor
